In [3]:
import pandas as pd

In [5]:
df = pd.read_csv("C:/Users/Badmesh/Downloads/sales_data.csv")

In [6]:
print(df.head())

   OrderID        Date     Product     Category  Quantity  UnitPrice
0     1031  2026-01-01  Smartphone  Electronics         3        800
1     1100  2026-01-02  Headphones  Accessories         2        150
2     1028  2026-01-02      Laptop  Electronics         2       1200
3     1089  2026-01-02      Laptop  Electronics         3       1200
4     1023  2026-01-02      Tablet  Electronics         4        450

In [7]:
df.loc[0]

OrderID             1031
Date          2026-01-01
Product       Smartphone
Category     Electronics
Quantity               3
UnitPrice            800
Name: 0, dtype: object

In [8]:
df.loc[0:19]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
6      1055  2026-01-03  Headphones  Accessories         1        150
7      1020  2026-01-03      Laptop  Electronics         1       1200
8      1082  2026-01-03  Smartphone  Electronics         4        800
9      1085  2026-01-04      Laptop  Electronics         1       1200
10     1088  2026-01-04      Tablet  Electronics         4        450
11     1094  2026-01-04      Tablet  Electronics         4        450
12     1017  2026-01-04  Smartwatch  Accessories         3        250
13     1063  2026-01-04  Smartwatch  Accessories         4        250
14     1056  2026-01-05  Smartwatch  Accessories         4        250
15     1091  2026-01-06  Smartwatch  Accessories         4        250
16     1027  2026-01-06      Tablet  Electronics         2        450
17     1061  2026-01-07  Headphones  Accessories         3        150
18     1058  2026-01-07      Laptop  Electronics         2       1200
19     1077  2026-01-07  Headphones  Accessories         2        150

In [9]:
df.iloc[0]

OrderID             1031
Date          2026-01-01
Product       Smartphone
Category     Electronics
Quantity               3
UnitPrice            800
Name: 0, dtype: object

In [10]:
df.iloc[0:10, 0:5]

   OrderID        Date     Product     Category  Quantity
0     1031  2026-01-01  Smartphone  Electronics         3
1     1100  2026-01-02  Headphones  Accessories         2
2     1028  2026-01-02      Laptop  Electronics         2
3     1089  2026-01-02      Laptop  Electronics         3
4     1023  2026-01-02      Tablet  Electronics         4
5     1072  2026-01-02  Smartphone  Electronics         4
6     1055  2026-01-03  Headphones  Accessories         1
7     1020  2026-01-03      Laptop  Electronics         1
8     1082  2026-01-03  Smartphone  Electronics         4
9     1085  2026-01-04      Laptop  Electronics         1

In [12]:
df[df["Quantity"] > 1000]

Empty DataFrame
Columns: [OrderID, Date, Product, Category, Quantity, UnitPrice]
Index: []

In [13]:
df[df["Quantity"] < 1000]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [14]:
df[df["Quantity"] <= 1000]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [15]:
df[df["Quantity"] <= 1000]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [21]:
df[(df["Quantity"] > 1000) & (df["UnitPrice"] > 200)]

Empty DataFrame
Columns: [OrderID, Date, Product, Category, Quantity, UnitPrice]
Index: []

In [22]:
df[(df["Quantity"] > 5000) | (df["UnitPrice"] > 1000)]

    OrderID        Date Product     Category  Quantity  UnitPrice
2      1028  2026-01-02  Laptop  Electronics         2       1200
3      1089  2026-01-02  Laptop  Electronics         3       1200
7      1020  2026-01-03  Laptop  Electronics         1       1200
9      1085  2026-01-04  Laptop  Electronics         1       1200
18     1058  2026-01-07  Laptop  Electronics         2       1200
23     1018  2026-01-08  Laptop  Electronics         2       1200
24     1087  2026-01-08  Laptop  Electronics         4       1200
36     1025  2026-01-12  Laptop  Electronics         3       1200
42     1048  2026-01-15  Laptop  Electronics         3       1200
43     1004  2026-01-15  Laptop  Electronics         2       1200
46     1044  2026-01-16  Laptop  Electronics         4       1200
47     1038  2026-01-17  Laptop  Electronics         2       1200
48     1084  2026-01-17  Laptop  Electronics         4       1200
50     1086  2026-01-18  Laptop  Electronics         1       1200
51     1097  2026-01-18  Laptop  Electronics         2       1200
66     1021  2026-01-22  Laptop  Electronics         1       1200
67     1095  2026-01-22  Laptop  Electronics         1       1200
68     1092  2026-01-22  Laptop  Electronics         1       1200
69     1052  2026-01-23  Laptop  Electronics         3       1200
71     1015  2026-01-24  Laptop  Electronics         4       1200
73     1019  2026-01-24  Laptop  Electronics         3       1200
78     1033  2026-01-26  Laptop  Electronics         4       1200
81     1010  2026-01-26  Laptop  Electronics         1       1200
87     1074  2026-01-28  Laptop  Electronics         3       1200
93     1035  2026-01-29  Laptop  Electronics         1       1200

In [23]:
df[~(df["Category"] == "UnitPrice")]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [24]:
df.sort_values("Product")

    OrderID        Date     Product     Category  Quantity  UnitPrice
77     1070  2026-01-26  Headphones  Accessories         1        150
64     1059  2026-01-21  Headphones  Accessories         2        150
65     1034  2026-01-22  Headphones  Accessories         1        150
57     1002  2026-01-20  Headphones  Accessories         3        150
54     1011  2026-01-19  Headphones  Accessories         2        150
..      ...         ...         ...          ...       ...        ...
44     1045  2026-01-15      Tablet  Electronics         3        450
72     1024  2026-01-24      Tablet  Electronics         1        450
53     1057  2026-01-19      Tablet  Electronics         2        450
84     1029  2026-01-28      Tablet  Electronics         4        450
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [27]:
df.sort_values("Product", ascending=True)

    OrderID        Date     Product     Category  Quantity  UnitPrice
77     1070  2026-01-26  Headphones  Accessories         1        150
64     1059  2026-01-21  Headphones  Accessories         2        150
65     1034  2026-01-22  Headphones  Accessories         1        150
57     1002  2026-01-20  Headphones  Accessories         3        150
54     1011  2026-01-19  Headphones  Accessories         2        150
..      ...         ...         ...          ...       ...        ...
44     1045  2026-01-15      Tablet  Electronics         3        450
72     1024  2026-01-24      Tablet  Electronics         1        450
53     1057  2026-01-19      Tablet  Electronics         2        450
84     1029  2026-01-28      Tablet  Electronics         4        450
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [28]:
df.sort_values("Product", ascending=False)

    OrderID        Date     Product     Category  Quantity  UnitPrice
99     1047  2026-01-30      Tablet  Electronics         3        450
16     1027  2026-01-06      Tablet  Electronics         2        450
44     1045  2026-01-15      Tablet  Electronics         3        450
53     1057  2026-01-19      Tablet  Electronics         2        450
41     1081  2026-01-15      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
65     1034  2026-01-22  Headphones  Accessories         1        150
33     1036  2026-01-12  Headphones  Accessories         3        150
22     1080  2026-01-08  Headphones  Accessories         3        150
63     1022  2026-01-21  Headphones  Accessories         1        150
57     1002  2026-01-20  Headphones  Accessories         3        150

[100 rows x 6 columns]

In [29]:
df["Category"] + df["UnitPrice"]

TypeError: can only concatenate str (not "int") to str